### ISSUE TITLE
Add sslrootcert host url option

### ISSUE THREAD

**Issue by igorvoltaic** [ClickHouse/clickhouse-kafka-connect#101]
That's not allowed at the moment and it is required in the cloud I'm using cloud. The only thing which stops me from migrating from jdbc sink

The parameter needs to me added in the same manner 'ssl' is appended in current version

**Comment by mzitnik** [comment]
@igorvoltaic can you please explain what is missing since the connector is currently is working with ClickHouse Cloud

**Comment by igorvoltaic** [comment]
Sure. Our cloud provider got managed ClickHouse and to connect that using ssl provider's root certificate has to be used
JDBC connection uri looks like `jdbc:clickhouse://{address}:{port}/db?ssl=true&sslrootcert=/etc/file/path.crt`

It would be nice to have an ability to parametrise connection
