### ISSUE TITLE
Go through the list of Clickhouse errors and see what should be retried

### ISSUE THREAD

**Issue by Paultagoras** [ClickHouse/clickhouse-kafka-connect#111]
**Is your feature request related to a problem? Please describe.**
We should go through the full list of error codes to see what make sense to retry.

See: https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp

**Comment by mzitnik** [comment]
List of codes that - I will not retry on  
code 3 and 4 this error is usually when you insert data into ClickHouse, but he expects to get more data so i would remove it from the list 
59 - query 
60 - if someone dropped the table or it is the wrong name of the table - I will not retry 
62 - query syntax no reason to retry if the query is wrong you can do anything about it - I will not retry 
73 - if we send an unknown format this is a bug
81 - same as 60, but for db
82 -
89 - we are using the wrong compression it's a bug
