### ISSUE TITLE
Small Issues from pre-beta testing

### ISSUE THREAD

**Issue by genzgd** [ClickHouse/clickhouse-kafka-connect#15]
- I couldn't find an actual zip file created by the `./gradlew` command.  I eventually got it to work by copying the full contents of the confluentArchive directory to `~/confluent-7.2.2/share/confluent-hub-components`
- In the Confluent Control Center UI, there are dots at the end of the labels for the configuration values
- Similarly, there is an `*` after the hostname label in the Confluent Control Center UI

**Comment by mzitnik** [comment]
the zip can be found in build/confluent,but we have published a release
