### ISSUE TITLE
Support for Schemaless 

### ISSUE THREAD

**Issue by mzitnik** [ClickHouse/clickhouse-kafka-connect#23]
When retrieving a SinkRecord from the Connect API the value type can be 

- Struct -> Schema with types 
- Map -> Map<String,Objects> without types 
- String -> unhandled 
- bytes[]  -> unhandled 

Currently supporting the Map type is partial we would like to refactor a more complete and stable solution

**Comment by blinkov** [comment]
@mzitnik "Shema" here is a mistype of Schema or something else?

**Comment by mzitnik** [comment]
Implemented & merge [https://github.com/ClickHouse/clickhouse-kafka-connect/pull/27](url)
