### ISSUE TITLE
Nested type support

### ISSUE THREAD

**Issue by Paultagoras** [ClickHouse/clickhouse-kafka-connect#286]
We should do a comparison between all Kafka types and all ClickHouse types, and make sure we have full coverage for all of them - both nested and flat as well.

**Comment by mshustov** [comment]
https://clickhouse.com/docs/en/operations/settings/settings#describe_include_subcolumns might help with parsing the nested type description

**Comment by jirislav** [comment]
Would be also nice to have a support for the similar `Tuple` type.

Btw, I'm considering to make a contribution for this. @Paultagoras You mentioned (https://github.com/ClickHouse/clickhouse-kafka-connect/pull/323#pullrequestreview-1890933062) you'd like to avoid recursion. Do you have any specific idea in mind, how to approach this?

Would you accept PR with Tuple/Nested support if I also used recursion? I think it's better to support it somehow and tune it later than to not support it at all for longer period of time.

**Comment by jirislav** [comment]
Okay, it was quite a heavy task, but it seems like I managed it, please review it:
- https://github.com/ClickHouse/clickhouse-kafka-connect/pull/368
- https://github.com/ClickHouse/clickhouse-docs/pull/2202

Disclaimer: I focused on Tuple & Variant types. Nested types are still not supported as this wasn't a priority for me.

**Comment by jirislav** [comment]
The Pull Request now includes support also for the Nested type (it was an easy change after all).

**Comment by dermasmid** [comment]
im seeing this error:
```
INFO 2024-05-29T14:39:51.163593458Z java.lang.IllegalArgumentException: DESCRIBE TABLE is never supposed to return Nested type. It should always yield its Array fields directly. at com.clickhouse.kafka.connect.sink.db.mapping.Column.extractColumn(Column.java:204) at com.clickhouse.kafka.connect.sink.db.mapping.Column.extractColumn(Column.java:159) at com.clickhouse.kafka.connect.sink.db.mapping.Column.extractColumn(Column.java:155) at com.clickhouse.kafka.connect.sink.db.helper.ClickHouseHelperClient.describeTable(ClickHouseHelperClient.java:220) at com.clickhouse.kafka.connect.sink.db.helper.ClickHouseHelperClient.extractTablesMapping(ClickHouseHelperClient.java:248) at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.updateMapping(ClickHouseWriter.java:123) at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.start(ClickHouseWriter.java:103) at com.clickhouse.kafka.connect.sink.ProxySinkTask.<init>(ProxySinkTask.java:61) at com.clickhouse.kafka.connect.sink.ClickHouseSinkTask.start(ClickHouseSinkTask.java:57) at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:329) at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:202) at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:259) at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:237) at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) at java.base/java.lang.Thread.run(Thread.java:840)

```

the logs dont include the table that caused it, so i dont have a repro yet
