### ISSUE TITLE
Config error connecting to clickhouse on port 80

### ISSUE THREAD

**Issue by kris-swann** [ClickHouse/clickhouse-kafka-connect#40]
Hello, we are trying to connect to our clickhouse cluster via chproxy which we have exposed on port 80.

However when we try to do that, we are seeing the following error:

```
        PUT /connectors/clickhouse-sink.cdc.structured-trait-updates.v0/config
        returned 400 (Bad Request): Connector configuration is invalid and
        contains the following 1 error(s):

        Invalid value 80 for configuration port: Value must be at least 1024

        You can also find the above list of errors at the endpoint
        `/connector-plugins/{connectorType}/config/validate`
```

Seems like the port number is restricted here:

https://github.com/ClickHouse/clickhouse-kafka-connect/blob/f408f62ba0d380d29b44eac7e1636103e5d826bb/src/main/java/com/clickhouse/kafka/connect/sink/ClickHouseSinkConfig.java#L108

Is there a reason for these bounds or can the range be expanded?

In meantime we will build from source, bumping that range from 1to Integer.MAX_VALUE

Thanks!

**Comment by mzitnik** [comment]
In Linux, in order to bind to port less than 1024 you need root access, so if you running chproxy internally I would recommend binding it to another port. I will fix it

**Comment by kris-swann** [comment]
ok, thank you for the info, i suppose we will have to update our networking to work within this limitation
