### ISSUE TITLE
Single steam with multiple destination dbs

### ISSUE THREAD

**Issue by kapopken** [ClickHouse/clickhouse-kafka-connect#41]
We have a multi-tenant environment where certain events are streamed along the same topic but need to be sinked into different databases.  Example events
```json
{
  "userName": "someUser",
  "tenantId": "tenantA"
}
```

we are required to store all tenant information into their own database. We would like to do this dynamically and without having to create a new connector per tenant to reduce onboarding of new tenants and maintainence.

**Comment by mzitnik** [comment]
Just verifying 
A single cluster with different databases.
[database_name].[table_name] = {tenantId}.{topic_name}

**Comment by kapopken** [comment]
Yes it is a replicated cluster.

**Comment by abhishekgahlot2** [comment]
@mzitnik is there a performance bottleneck if i patch the repo and connect to multiple databases for different topics but same clickhouse instance?

**Comment by mzitnik** [comment]
@abhishekgahlot2 There should not be a bottleneck. Why do need it? (for multi-tenet)
If it's only a few of them I would recommend running several instances of  connect.

**Comment by abhishekgahlot2** [comment]
@mzitnik yeah i am thinking topics.regex should be fine for wildcard but database could be in thousands so spinning up connectors could take time.

**Comment by mzitnik** [comment]
We need to think about the best way to implement it since we will also need to open many clients.
What is the urgency for it?

**Comment by abhishekgahlot2** [comment]
Actually we need it urgently for a usecase where customer database can have isolated events coming from multiple dynamic topics.

for now dynamic topic to table name mapping i am thinking is possible via topics.regex lets via `topics.regex=customers_.*`

and publish to `customers-adam`, or `customer-abhi` without explicitly specifying in connector config  let me know if this is wrong.

For database connect in codebase i see most of the clickhouse db connection builder string uses database as a parameter i am wondering if for pushing data in the end not when verifying schema we can get it dynamically similarly like topics.regex too. wdyt?

however guide on building project locally to patch up the library would be really helpful

**Comment by mzitnik** [comment]
Can you provide a real example of the data and mapping?
Do you have multiple topics, or the tenant should extracted from the event ?

**Comment by abhishekgahlot2** [comment]
we have lambdas that will push to msk they will have information about customer and organization. so a payload might look like on high level 

```
{
	"organization": "abc",
	"event_root": "monitor_logs",
	"data.a": string,
	"data.b": number,
	....
}

```

From lambda i know which topic to insert into which is `monitor_logs` but organization `abc` will be the database in clickhouse that will preserve the events and we will also have acl and isolated events for each organization.

**Comment by abhishekgahlot2** [comment]
Basically first two fields `organization` and `event_root` is defining the location of clickhouse destination which is database name and topic name.

**Comment by mzitnik** [comment]
The way we planned to implement it, you should run a transformation that extracts {organization}.{event_root}, and in connect, we should push it to different databases. This is actually creating a virtual topic in Kafka Connect.
Another question is every tenet has multiple tables (the table name is extracted from `event_root`)

**Comment by abhishekgahlot2** [comment]
I am trying to extract the topic and tenant from the record herein 

```
private void doInsert(List<Record> records, RangeContainer rangeContainer) {
        if (records == null || records.isEmpty()) {
            LOGGER.info("doInsert - No records to insert.");
            return;
        }
        QueryIdentifier queryId = new QueryIdentifier(records.get(0).getRecordOffsetContainer().getTopic(), records.get(0).getRecordOffsetContainer().getPartition(),
                rangeContainer.getMinOffset(), rangeContainer.getMaxOffset(),
                UUID.randomUUID().toString());
    }
```
    
  
 and in ClickhouseWriter have something like
    
```
private static ClickHouseHelperClient createClient(String database) {
		ClickHouseHelperClient chc1 = new ClickHouseHelperClient.ClickHouseClientBuilder
				.setDatabase(database)
				.build();
		return chc;
	}
```

Do you think this could be a viable solution i see records in doInsert are batch records so not sure how to combine them.

**Comment by abhishekgahlot2** [comment]
I am also thinking an alternative strategy to above code is to not extract record but use topic name like `organisation-name/table-name` and then split while writing to clickhouse to avoid writing more logic. so topic name will look like `abc/monitor-logs` pointing to `abc` database and `monitor-logs` table.

**Comment by mzitnik** [comment]
The only thing that I am missing here is how to set the db on the client side. It looks like it is provided using the URL.
So I need to check how it is done on the demand.

**Comment by abhishekgahlot2** [comment]
I shared some approach here: https://github.com/ClickHouse/clickhouse-kafka-connect/discussions/322
build and tested on confluent. i am able to push to multiple database but now i am worried about too many topics. so trying using key rather than extracting database or table from topic.

**Comment by mzitnik** [comment]
if you are using https://docs.confluent.io/platform/current/connect/transforms/extracttopic.html#extracttopic you can extract {database}.{table} from the key it will create a virtual topic and than before insert you need to split by . a set database and table

**Comment by mzitnik** [comment]
Just to verify, do you currently have a working solution?

**Comment by abhishekgahlot2** [comment]
hacky solution (need to clean it up) that modifies the mutation request and extract database and table from topic but won’t scale because having both db and table name in topic means too many topic for cluster to handle right?

We hit the limit of 6k partitions because of this.

**Comment by abhishekgahlot2** [comment]
hi @mzitnik I see new code for multi-database support in the connector does it mean I can use any database and any table as a part of the connector now using topic with regex?

**Comment by mzitnik** [comment]
@abhishekgahlot2 Yes, we have developed it recently. We have yet to manage to write documentation. There are actually two configs: one that enables the feature and the other that sets the separator. It would be best if you used https://docs.confluent.io/platform/current/connect/transforms/extracttopic.html#extracttopic to extract db/table name according to a field from your content and build a virtual topic.

**Comment by abhishekgahlot2** [comment]
Oh, are the new changes using extract topic configuration and is only supported for confluent?

**Comment by mzitnik** [comment]
@abhishekgahlot2 are you running the sink using confluent platform?

**Comment by abhishekgahlot2** [comment]
No, I am using Kafka on AWS. but I patched the library to use keys and made it work. 
so key for table and topics for the database using topics.regex. I believe this avoids making too many topics for me.

And rest of the code looks very similar to your PR, patching the mutation request and creating a new builder for clickhouse database.

```
Map<String, List<Record>> dataRecords = records.stream()
                .map(v -> Record.convert(v))
                .filter(v -> v.getKafkaKey() != null)
                .collect(Collectors.groupingBy(Record::getKafkaKey));

        statistics.recordProcessingTime(processingTime);
        for (String topicAndPartition : dataRecords.keySet()) {
            // Running on each kafka key.
            List<Record> rec = dataRecords.get(topicAndPartition);
            processing.doLogic(rec);
        }
```

I think my use case is solved by this, I am not creating too many topics, not making Kafka unstable and able to achieve multitenancy. Sometimes though data takes 1-2 minutes to be visible in clickhouse initially but when it visible first time after that its almost instant for upcoming records.

**Comment by mzitnik** [comment]
@abhishekgahlot2 
Sorry for looping back on this. As I understand, you are using AWS MSK and running the `clickhouse-kafka-sink` and. it looks like we can run Confluent transformation there (Need to verify)
The only concern with the approach you took when using the `key` is that this can imbalance the number of messages on each partition.

**Comment by mzitnik** [comment]
We are checking the possibility of deploying a transformation with `clickhouse-kafka-connect` to see if it will run on MSK as expected. Thanks to @Paultagoras, we will have answers soon.

**Comment by abhishekgahlot2** [comment]
@Paultagoras this is awesome thanks

**Comment by abhishekgahlot2** [comment]
Trying to understand, using current build now to handle 

Does this look correct 

```connector.class=com.clickhouse.kafka.connect.ClickHouseSinkConnector
dbTopicSplitChar=.
tasks.max=2
topics.regex=[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.[t][a][b][l][e][_].*
ssl=false
hostname=host
database=default
enableDbTopicSplit=true
```

And sending json to topic UUID.table_anything will put records to UUID -> database and table_anything -> table.
