### ISSUE TITLE
Aws Msk connector config

### ISSUE THREAD

**Issue by tranhoangvuit** [ClickHouse/clickhouse-kafka-connect#48]
Hi, thank you for releasing the new version 0.05 to support msk. But can I have an example or tutorial to config on aws mask ? very appreciate for this help. I tried it on my config but looks like it doesn't work. This is my connector config
```
connector.class=com.clickhouse.kafka.connect.sink
tasks.max=2
topics=Events_Test
schema.enable=false
key.converter.schemas.enable=false
hostname=https://demo.us-east-2.aws.clickhouse.cloud
password=demopass
database=demopassword
aws.region=us-east-1
port=8443
value.converter=org.apache.kafka.connect.storage.StringConverter
errors.log.enable=true
key.converter=org.apache.kafka.connect.storage.StringConverter
username=default
```

**Comment by clamoris** [comment]
Hi! Try something like this.

Hostname should be without schema.

```
connector.class=com.clickhouse.kafka.connect.ClickHouseSinkConnector
tasks.max=1
topics=<topic_name>
ssl=true
security.protocol=SSL
hostname=<hostname>
database=default
password=<password>
ssl.truststore.location=/tmp/kafka.client.truststore.jks
port=8443
value.converter.schemas.enable=false
value.converter=org.apache.kafka.connect.json.JsonConverter
exactlyOnce=true
username=default
schemas.enable=false
```

**Comment by tranhoangvuit** [comment]
Thanks @clamoris , but I still got an issue with the connection to click house database.
`om.clickhouse.client.ClickHouseException: connect timed out, server ClickHouseNode [uri=https://demo.us-east-2.aws.clickhouse.cloud:8443/default, options={sslmode=STRICT}]`
do you have any idea on this error? thanks.

**Comment by clamoris** [comment]
Is MSK Connect allowed to go to the [internet](https://docs.aws.amazon.com/msk/latest/developerguide/msk-connect-internet-access.html)?

It was suggested by the ClickHouse team.

**Comment by tranhoangvuit** [comment]
Thank @clamoris so much.

**Comment by mshustov** [comment]
closed by https://github.com/ClickHouse/clickhouse-docs/pull/740
