### ISSUE TITLE
Supprting ClickHouse JSON Type

### ISSUE THREAD

**Issue by mzitnik** [ClickHouse/clickhouse-kafka-connect#6]
Kafka Connect SinkRecord is supporting nested types 
It should be translated to JSON Type in ClickHouse

**Comment by amit-cashify** [comment]
Any timeline on this?

**Comment by amit-cashify** [comment]
> Hi @amit-cashify - the short answer is that we're waiting for official support of the [JSON](https://clickhouse.com/docs/en/sql-reference/data-types/json) type, as it's currently considered experimental.

I am also waiting on that to be production ready. Do you know of an ETA for official support of JSON type?
